targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: frontend|lib/qraphql/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: frontend|lib/qraphql/schema.graphql
